### ISSUE TITLE
Remove spying in DMs

### ISSUE THREAD

**Issue by domin-mnd** [DanBot-Hosting/DanBotHostingStats#379]
Why would a discord bot resend messages from DMs to a moderation channel? Is this considered spying or stalking?

![Screenshot](https://s.domin.pro/wyb/raw)

https://github.com/DanBot-Hosting/DanBotHostingStats/blob/f57a15e4ce89d1aee7181b0b76c15d916c17a9ac/bot/discord/events/message.js#L30-L37

**Comment by DEV-DIBSTER** [comment]
@danielpmc

**Comment by danielpmc** [comment]
> Why would a discord bot resend messages from DMs to a moderation channel? Is this considered spying or stalking?
> 
> ![Screenshot](https://s.domin.pro/wyb/raw)
> 
> https://github.com/DanBot-Hosting/DanBotHostingStats/blob/f57a15e4ce89d1aee7181b0b76c15d916c17a9ac/bot/discord/events/message.js#L30-L37

It's from DBH V1. People who were banned, etc, could DM the bot and get a response from me or one of the other admins. The channel is still in place today but is no longer used. Only people with admin+ can see it. Its just something that wasn't removed since the original DBH. feel free to make a PR to remove it

**Comment by DEV-DIBSTER** [comment]
This has been completed. Thank you @domin-mnd for pointing this out.
